// Edge Runtime entrypoint (self-host pattern).
// Auto-generated by selfhost/scripts/build-functions.sh — regenerate after editing
// any supabase/functions/*/index.ts by running that script (requires Deno installed).
//
// Each bundled function module below exports the standard Edge Function handler
// shape:  ServeHandlerWithContext  (named export `handler`) OR default export.
// The edge-runtime interprets `func.path` as the URL path under /functions/v1/.

import { handler as create_website_booking } from "./functions/create-website-booking.js";
// ... more function modules are appended here by build-functions.sh
