/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminWhatsappConfigRouteImport } from './routes/admin.whatsapp-config'
import { Route as AdminSuscripcionesRouteImport } from './routes/admin.suscripciones'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminPreciosRouteImport } from './routes/admin.precios'
import { Route as AdminNotificacionesRouteImport } from './routes/admin.notificaciones'
import { Route as AdminMensajesRouteImport } from './routes/admin.mensajes'
import { Route as AdminMapaDemandaRouteImport } from './routes/admin.mapa-demanda'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsKipperRouteImport } from './routes/admin.leads-kipper'
import { Route as AdminFinanzasRouteImport } from './routes/admin.finanzas'
import { Route as AdminFacturasRouteImport } from './routes/admin.facturas'
import { Route as AdminEarlyAccessRouteImport } from './routes/admin.early-access'
import { Route as AdminDisponibilidadRouteImport } from './routes/admin.disponibilidad'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as AdminBotmakerRouteImport } from './routes/admin.botmaker'
import { Route as AdminAppConfigRouteImport } from './routes/admin.app-config'
import { Route as PublicReservarRouteImport } from './routes/_public.reservar'
import { Route as PublicGraciasRouteImport } from './routes/_public.gracias'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminWhatsappConfigRoute = AdminWhatsappConfigRouteImport.update({
  id: '/whatsapp-config',
  path: '/whatsapp-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuscripcionesRoute = AdminSuscripcionesRouteImport.update({
  id: '/suscripciones',
  path: '/suscripciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreciosRoute = AdminPreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesRoute = AdminNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensajesRoute = AdminMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapaDemandaRoute = AdminMapaDemandaRouteImport.update({
  id: '/mapa-demanda',
  path: '/mapa-demanda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsKipperRoute = AdminLeadsKipperRouteImport.update({
  id: '/leads-kipper',
  path: '/leads-kipper',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanzasRoute = AdminFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturasRoute = AdminFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEarlyAccessRoute = AdminEarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisponibilidadRoute = AdminDisponibilidadRouteImport.update({
  id: '/disponibilidad',
  path: '/disponibilidad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotmakerRoute = AdminBotmakerRouteImport.update({
  id: '/botmaker',
  path: '/botmaker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppConfigRoute = AdminAppConfigRouteImport.update({
  id: '/app-config',
  path: '/app-config',
  getParentRoute: () => AdminRoute,
} as any)
const PublicReservarRoute = PublicReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGraciasRoute = PublicGraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/gracias': typeof PublicGraciasRoute
  '/reservar': typeof PublicReservarRoute
  '/admin/app-config': typeof AdminAppConfigRoute
  '/admin/botmaker': typeof AdminBotmakerRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/leads-kipper': typeof AdminLeadsKipperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mapa-demanda': typeof AdminMapaDemandaRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/whatsapp-config': typeof AdminWhatsappConfigRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/gracias': typeof PublicGraciasRoute
  '/reservar': typeof PublicReservarRoute
  '/admin/app-config': typeof AdminAppConfigRoute
  '/admin/botmaker': typeof AdminBotmakerRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/leads-kipper': typeof AdminLeadsKipperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mapa-demanda': typeof AdminMapaDemandaRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/whatsapp-config': typeof AdminWhatsappConfigRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/gracias': typeof PublicGraciasRoute
  '/_public/reservar': typeof PublicReservarRoute
  '/admin/app-config': typeof AdminAppConfigRoute
  '/admin/botmaker': typeof AdminBotmakerRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/leads-kipper': typeof AdminLeadsKipperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mapa-demanda': typeof AdminMapaDemandaRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/whatsapp-config': typeof AdminWhatsappConfigRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/gracias'
    | '/reservar'
    | '/admin/app-config'
    | '/admin/botmaker'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/early-access'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/leads-kipper'
    | '/admin/login'
    | '/admin/mapa-demanda'
    | '/admin/mensajes'
    | '/admin/notificaciones'
    | '/admin/precios'
    | '/admin/reservas'
    | '/admin/suscripciones'
    | '/admin/whatsapp-config'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/gracias'
    | '/reservar'
    | '/admin/app-config'
    | '/admin/botmaker'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/early-access'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/leads-kipper'
    | '/admin/login'
    | '/admin/mapa-demanda'
    | '/admin/mensajes'
    | '/admin/notificaciones'
    | '/admin/precios'
    | '/admin/reservas'
    | '/admin/suscripciones'
    | '/admin/whatsapp-config'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/gracias'
    | '/_public/reservar'
    | '/admin/app-config'
    | '/admin/botmaker'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/early-access'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/leads-kipper'
    | '/admin/login'
    | '/admin/mapa-demanda'
    | '/admin/mensajes'
    | '/admin/notificaciones'
    | '/admin/precios'
    | '/admin/reservas'
    | '/admin/suscripciones'
    | '/admin/whatsapp-config'
    | '/_public/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/whatsapp-config': {
      id: '/admin/whatsapp-config'
      path: '/whatsapp-config'
      fullPath: '/admin/whatsapp-config'
      preLoaderRoute: typeof AdminWhatsappConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suscripciones': {
      id: '/admin/suscripciones'
      path: '/suscripciones'
      fullPath: '/admin/suscripciones'
      preLoaderRoute: typeof AdminSuscripcionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precios': {
      id: '/admin/precios'
      path: '/precios'
      fullPath: '/admin/precios'
      preLoaderRoute: typeof AdminPreciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificaciones': {
      id: '/admin/notificaciones'
      path: '/notificaciones'
      fullPath: '/admin/notificaciones'
      preLoaderRoute: typeof AdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensajes': {
      id: '/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AdminMensajesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapa-demanda': {
      id: '/admin/mapa-demanda'
      path: '/mapa-demanda'
      fullPath: '/admin/mapa-demanda'
      preLoaderRoute: typeof AdminMapaDemandaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads-kipper': {
      id: '/admin/leads-kipper'
      path: '/leads-kipper'
      fullPath: '/admin/leads-kipper'
      preLoaderRoute: typeof AdminLeadsKipperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzas': {
      id: '/admin/finanzas'
      path: '/finanzas'
      fullPath: '/admin/finanzas'
      preLoaderRoute: typeof AdminFinanzasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturas': {
      id: '/admin/facturas'
      path: '/facturas'
      fullPath: '/admin/facturas'
      preLoaderRoute: typeof AdminFacturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/early-access': {
      id: '/admin/early-access'
      path: '/early-access'
      fullPath: '/admin/early-access'
      preLoaderRoute: typeof AdminEarlyAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disponibilidad': {
      id: '/admin/disponibilidad'
      path: '/disponibilidad'
      fullPath: '/admin/disponibilidad'
      preLoaderRoute: typeof AdminDisponibilidadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/botmaker': {
      id: '/admin/botmaker'
      path: '/botmaker'
      fullPath: '/admin/botmaker'
      preLoaderRoute: typeof AdminBotmakerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/app-config': {
      id: '/admin/app-config'
      path: '/app-config'
      fullPath: '/admin/app-config'
      preLoaderRoute: typeof AdminAppConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/reservar': {
      id: '/_public/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof PublicReservarRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gracias': {
      id: '/_public/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof PublicGraciasRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicGraciasRoute: typeof PublicGraciasRoute
  PublicReservarRoute: typeof PublicReservarRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicGraciasRoute: PublicGraciasRoute,
  PublicReservarRoute: PublicReservarRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAppConfigRoute: typeof AdminAppConfigRoute
  AdminBotmakerRoute: typeof AdminBotmakerRoute
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDisponibilidadRoute: typeof AdminDisponibilidadRoute
  AdminEarlyAccessRoute: typeof AdminEarlyAccessRoute
  AdminFacturasRoute: typeof AdminFacturasRoute
  AdminFinanzasRoute: typeof AdminFinanzasRoute
  AdminLeadsKipperRoute: typeof AdminLeadsKipperRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMapaDemandaRoute: typeof AdminMapaDemandaRoute
  AdminMensajesRoute: typeof AdminMensajesRoute
  AdminNotificacionesRoute: typeof AdminNotificacionesRoute
  AdminPreciosRoute: typeof AdminPreciosRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminSuscripcionesRoute: typeof AdminSuscripcionesRoute
  AdminWhatsappConfigRoute: typeof AdminWhatsappConfigRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppConfigRoute: AdminAppConfigRoute,
  AdminBotmakerRoute: AdminBotmakerRoute,
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDisponibilidadRoute: AdminDisponibilidadRoute,
  AdminEarlyAccessRoute: AdminEarlyAccessRoute,
  AdminFacturasRoute: AdminFacturasRoute,
  AdminFinanzasRoute: AdminFinanzasRoute,
  AdminLeadsKipperRoute: AdminLeadsKipperRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMapaDemandaRoute: AdminMapaDemandaRoute,
  AdminMensajesRoute: AdminMensajesRoute,
  AdminNotificacionesRoute: AdminNotificacionesRoute,
  AdminPreciosRoute: AdminPreciosRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminSuscripcionesRoute: AdminSuscripcionesRoute,
  AdminWhatsappConfigRoute: AdminWhatsappConfigRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
