/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as OperatorSemanaRouteImport } from './routes/operator.semana'
import { Route as OperatorPerfilRouteImport } from './routes/operator.perfil'
import { Route as OperatorPendientesRouteImport } from './routes/operator.pendientes'
import { Route as OperatorLoginRouteImport } from './routes/operator.login'
import { Route as OperatorHoyRouteImport } from './routes/operator.hoy'
import { Route as AdminWhatsappConfigRouteImport } from './routes/admin.whatsapp-config'
import { Route as AdminSuscripcionesRouteImport } from './routes/admin.suscripciones'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminPreciosRouteImport } from './routes/admin.precios'
import { Route as AdminNotificacionesRouteImport } from './routes/admin.notificaciones'
import { Route as AdminMensajesRouteImport } from './routes/admin.mensajes'
import { Route as AdminMapaDemandaRouteImport } from './routes/admin.mapa-demanda'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsKipperRouteImport } from './routes/admin.leads-kipper'
import { Route as AdminFinanzasRouteImport } from './routes/admin.finanzas'
import { Route as AdminFacturasRouteImport } from './routes/admin.facturas'
import { Route as AdminEarlyAccessRouteImport } from './routes/admin.early-access'
import { Route as AdminDisponibilidadRouteImport } from './routes/admin.disponibilidad'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as AdminBotmakerRouteImport } from './routes/admin.botmaker'
import { Route as AdminAppConfigRouteImport } from './routes/admin.app-config'
import { Route as PublicReservarRouteImport } from './routes/_public.reservar'
import { Route as PublicGraciasRouteImport } from './routes/_public.gracias'
import { Route as OperatorReservaBookingIdRouteImport } from './routes/operator.reserva.$bookingId'
import { Route as AdminFacturasInvoiceIdRouteImport } from './routes/admin.facturas_.$invoiceId'
import { Route as PublicComprobantePublicTokenRouteImport } from './routes/_public.comprobante.$publicToken'

const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const OperatorSemanaRoute = OperatorSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPerfilRoute = OperatorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorPendientesRoute = OperatorPendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorLoginRoute = OperatorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorHoyRoute = OperatorHoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => OperatorRoute,
} as any)
const AdminWhatsappConfigRoute = AdminWhatsappConfigRouteImport.update({
  id: '/whatsapp-config',
  path: '/whatsapp-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuscripcionesRoute = AdminSuscripcionesRouteImport.update({
  id: '/suscripciones',
  path: '/suscripciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreciosRoute = AdminPreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesRoute = AdminNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensajesRoute = AdminMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapaDemandaRoute = AdminMapaDemandaRouteImport.update({
  id: '/mapa-demanda',
  path: '/mapa-demanda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsKipperRoute = AdminLeadsKipperRouteImport.update({
  id: '/leads-kipper',
  path: '/leads-kipper',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanzasRoute = AdminFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturasRoute = AdminFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEarlyAccessRoute = AdminEarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisponibilidadRoute = AdminDisponibilidadRouteImport.update({
  id: '/disponibilidad',
  path: '/disponibilidad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotmakerRoute = AdminBotmakerRouteImport.update({
  id: '/botmaker',
  path: '/botmaker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppConfigRoute = AdminAppConfigRouteImport.update({
  id: '/app-config',
  path: '/app-config',
  getParentRoute: () => AdminRoute,
} as any)
const PublicReservarRoute = PublicReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGraciasRoute = PublicGraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => PublicRoute,
} as any)
const OperatorReservaBookingIdRoute =
  OperatorReservaBookingIdRouteImport.update({
    id: '/reserva/$bookingId',
    path: '/reserva/$bookingId',
    getParentRoute: () => OperatorRoute,
  } as any)
const AdminFacturasInvoiceIdRoute = AdminFacturasInvoiceIdRouteImport.update({
  id: '/facturas_/$invoiceId',
  path: '/facturas/$invoiceId',
  getParentRoute: () => AdminRoute,
} as any)
const PublicComprobantePublicTokenRoute =
  PublicComprobantePublicTokenRouteImport.update({
    id: '/comprobante/$publicToken',
    path: '/comprobante/$publicToken',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/operator': typeof OperatorRouteWithChildren
  '/gracias': typeof PublicGraciasRoute
  '/reservar': typeof PublicReservarRoute
  '/admin/app-config': typeof AdminAppConfigRoute
  '/admin/botmaker': typeof AdminBotmakerRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/leads-kipper': typeof AdminLeadsKipperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mapa-demanda': typeof AdminMapaDemandaRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/whatsapp-config': typeof AdminWhatsappConfigRoute
  '/operator/hoy': typeof OperatorHoyRoute
  '/operator/login': typeof OperatorLoginRoute
  '/operator/pendientes': typeof OperatorPendientesRoute
  '/operator/perfil': typeof OperatorPerfilRoute
  '/operator/semana': typeof OperatorSemanaRoute
  '/admin/': typeof AdminIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/comprobante/$publicToken': typeof PublicComprobantePublicTokenRoute
  '/admin/facturas/$invoiceId': typeof AdminFacturasInvoiceIdRoute
  '/operator/reserva/$bookingId': typeof OperatorReservaBookingIdRoute
}
export interface FileRoutesByTo {
  '/gracias': typeof PublicGraciasRoute
  '/reservar': typeof PublicReservarRoute
  '/admin/app-config': typeof AdminAppConfigRoute
  '/admin/botmaker': typeof AdminBotmakerRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/leads-kipper': typeof AdminLeadsKipperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mapa-demanda': typeof AdminMapaDemandaRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/whatsapp-config': typeof AdminWhatsappConfigRoute
  '/operator/hoy': typeof OperatorHoyRoute
  '/operator/login': typeof OperatorLoginRoute
  '/operator/pendientes': typeof OperatorPendientesRoute
  '/operator/perfil': typeof OperatorPerfilRoute
  '/operator/semana': typeof OperatorSemanaRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/comprobante/$publicToken': typeof PublicComprobantePublicTokenRoute
  '/admin/facturas/$invoiceId': typeof AdminFacturasInvoiceIdRoute
  '/operator/reserva/$bookingId': typeof OperatorReservaBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/operator': typeof OperatorRouteWithChildren
  '/_public/gracias': typeof PublicGraciasRoute
  '/_public/reservar': typeof PublicReservarRoute
  '/admin/app-config': typeof AdminAppConfigRoute
  '/admin/botmaker': typeof AdminBotmakerRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/early-access': typeof AdminEarlyAccessRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/finanzas': typeof AdminFinanzasRoute
  '/admin/leads-kipper': typeof AdminLeadsKipperRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mapa-demanda': typeof AdminMapaDemandaRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/suscripciones': typeof AdminSuscripcionesRoute
  '/admin/whatsapp-config': typeof AdminWhatsappConfigRoute
  '/operator/hoy': typeof OperatorHoyRoute
  '/operator/login': typeof OperatorLoginRoute
  '/operator/pendientes': typeof OperatorPendientesRoute
  '/operator/perfil': typeof OperatorPerfilRoute
  '/operator/semana': typeof OperatorSemanaRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/_public/comprobante/$publicToken': typeof PublicComprobantePublicTokenRoute
  '/admin/facturas_/$invoiceId': typeof AdminFacturasInvoiceIdRoute
  '/operator/reserva/$bookingId': typeof OperatorReservaBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/operator'
    | '/gracias'
    | '/reservar'
    | '/admin/app-config'
    | '/admin/botmaker'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/early-access'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/leads-kipper'
    | '/admin/login'
    | '/admin/mapa-demanda'
    | '/admin/mensajes'
    | '/admin/notificaciones'
    | '/admin/precios'
    | '/admin/reservas'
    | '/admin/suscripciones'
    | '/admin/whatsapp-config'
    | '/operator/hoy'
    | '/operator/login'
    | '/operator/pendientes'
    | '/operator/perfil'
    | '/operator/semana'
    | '/admin/'
    | '/operator/'
    | '/comprobante/$publicToken'
    | '/admin/facturas/$invoiceId'
    | '/operator/reserva/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/gracias'
    | '/reservar'
    | '/admin/app-config'
    | '/admin/botmaker'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/early-access'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/leads-kipper'
    | '/admin/login'
    | '/admin/mapa-demanda'
    | '/admin/mensajes'
    | '/admin/notificaciones'
    | '/admin/precios'
    | '/admin/reservas'
    | '/admin/suscripciones'
    | '/admin/whatsapp-config'
    | '/operator/hoy'
    | '/operator/login'
    | '/operator/pendientes'
    | '/operator/perfil'
    | '/operator/semana'
    | '/'
    | '/admin'
    | '/operator'
    | '/comprobante/$publicToken'
    | '/admin/facturas/$invoiceId'
    | '/operator/reserva/$bookingId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/operator'
    | '/_public/gracias'
    | '/_public/reservar'
    | '/admin/app-config'
    | '/admin/botmaker'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/early-access'
    | '/admin/facturas'
    | '/admin/finanzas'
    | '/admin/leads-kipper'
    | '/admin/login'
    | '/admin/mapa-demanda'
    | '/admin/mensajes'
    | '/admin/notificaciones'
    | '/admin/precios'
    | '/admin/reservas'
    | '/admin/suscripciones'
    | '/admin/whatsapp-config'
    | '/operator/hoy'
    | '/operator/login'
    | '/operator/pendientes'
    | '/operator/perfil'
    | '/operator/semana'
    | '/_public/'
    | '/admin/'
    | '/operator/'
    | '/_public/comprobante/$publicToken'
    | '/admin/facturas_/$invoiceId'
    | '/operator/reserva/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  OperatorRoute: typeof OperatorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/operator/semana': {
      id: '/operator/semana'
      path: '/semana'
      fullPath: '/operator/semana'
      preLoaderRoute: typeof OperatorSemanaRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/perfil': {
      id: '/operator/perfil'
      path: '/perfil'
      fullPath: '/operator/perfil'
      preLoaderRoute: typeof OperatorPerfilRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/pendientes': {
      id: '/operator/pendientes'
      path: '/pendientes'
      fullPath: '/operator/pendientes'
      preLoaderRoute: typeof OperatorPendientesRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/login': {
      id: '/operator/login'
      path: '/login'
      fullPath: '/operator/login'
      preLoaderRoute: typeof OperatorLoginRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/hoy': {
      id: '/operator/hoy'
      path: '/hoy'
      fullPath: '/operator/hoy'
      preLoaderRoute: typeof OperatorHoyRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/admin/whatsapp-config': {
      id: '/admin/whatsapp-config'
      path: '/whatsapp-config'
      fullPath: '/admin/whatsapp-config'
      preLoaderRoute: typeof AdminWhatsappConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suscripciones': {
      id: '/admin/suscripciones'
      path: '/suscripciones'
      fullPath: '/admin/suscripciones'
      preLoaderRoute: typeof AdminSuscripcionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precios': {
      id: '/admin/precios'
      path: '/precios'
      fullPath: '/admin/precios'
      preLoaderRoute: typeof AdminPreciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificaciones': {
      id: '/admin/notificaciones'
      path: '/notificaciones'
      fullPath: '/admin/notificaciones'
      preLoaderRoute: typeof AdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensajes': {
      id: '/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AdminMensajesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapa-demanda': {
      id: '/admin/mapa-demanda'
      path: '/mapa-demanda'
      fullPath: '/admin/mapa-demanda'
      preLoaderRoute: typeof AdminMapaDemandaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads-kipper': {
      id: '/admin/leads-kipper'
      path: '/leads-kipper'
      fullPath: '/admin/leads-kipper'
      preLoaderRoute: typeof AdminLeadsKipperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finanzas': {
      id: '/admin/finanzas'
      path: '/finanzas'
      fullPath: '/admin/finanzas'
      preLoaderRoute: typeof AdminFinanzasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturas': {
      id: '/admin/facturas'
      path: '/facturas'
      fullPath: '/admin/facturas'
      preLoaderRoute: typeof AdminFacturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/early-access': {
      id: '/admin/early-access'
      path: '/early-access'
      fullPath: '/admin/early-access'
      preLoaderRoute: typeof AdminEarlyAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disponibilidad': {
      id: '/admin/disponibilidad'
      path: '/disponibilidad'
      fullPath: '/admin/disponibilidad'
      preLoaderRoute: typeof AdminDisponibilidadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/botmaker': {
      id: '/admin/botmaker'
      path: '/botmaker'
      fullPath: '/admin/botmaker'
      preLoaderRoute: typeof AdminBotmakerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/app-config': {
      id: '/admin/app-config'
      path: '/app-config'
      fullPath: '/admin/app-config'
      preLoaderRoute: typeof AdminAppConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/reservar': {
      id: '/_public/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof PublicReservarRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gracias': {
      id: '/_public/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof PublicGraciasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/operator/reserva/$bookingId': {
      id: '/operator/reserva/$bookingId'
      path: '/reserva/$bookingId'
      fullPath: '/operator/reserva/$bookingId'
      preLoaderRoute: typeof OperatorReservaBookingIdRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/admin/facturas_/$invoiceId': {
      id: '/admin/facturas_/$invoiceId'
      path: '/facturas/$invoiceId'
      fullPath: '/admin/facturas/$invoiceId'
      preLoaderRoute: typeof AdminFacturasInvoiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/comprobante/$publicToken': {
      id: '/_public/comprobante/$publicToken'
      path: '/comprobante/$publicToken'
      fullPath: '/comprobante/$publicToken'
      preLoaderRoute: typeof PublicComprobantePublicTokenRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicGraciasRoute: typeof PublicGraciasRoute
  PublicReservarRoute: typeof PublicReservarRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicComprobantePublicTokenRoute: typeof PublicComprobantePublicTokenRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicGraciasRoute: PublicGraciasRoute,
  PublicReservarRoute: PublicReservarRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicComprobantePublicTokenRoute: PublicComprobantePublicTokenRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAppConfigRoute: typeof AdminAppConfigRoute
  AdminBotmakerRoute: typeof AdminBotmakerRoute
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDisponibilidadRoute: typeof AdminDisponibilidadRoute
  AdminEarlyAccessRoute: typeof AdminEarlyAccessRoute
  AdminFacturasRoute: typeof AdminFacturasRoute
  AdminFinanzasRoute: typeof AdminFinanzasRoute
  AdminLeadsKipperRoute: typeof AdminLeadsKipperRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMapaDemandaRoute: typeof AdminMapaDemandaRoute
  AdminMensajesRoute: typeof AdminMensajesRoute
  AdminNotificacionesRoute: typeof AdminNotificacionesRoute
  AdminPreciosRoute: typeof AdminPreciosRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminSuscripcionesRoute: typeof AdminSuscripcionesRoute
  AdminWhatsappConfigRoute: typeof AdminWhatsappConfigRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFacturasInvoiceIdRoute: typeof AdminFacturasInvoiceIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppConfigRoute: AdminAppConfigRoute,
  AdminBotmakerRoute: AdminBotmakerRoute,
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDisponibilidadRoute: AdminDisponibilidadRoute,
  AdminEarlyAccessRoute: AdminEarlyAccessRoute,
  AdminFacturasRoute: AdminFacturasRoute,
  AdminFinanzasRoute: AdminFinanzasRoute,
  AdminLeadsKipperRoute: AdminLeadsKipperRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMapaDemandaRoute: AdminMapaDemandaRoute,
  AdminMensajesRoute: AdminMensajesRoute,
  AdminNotificacionesRoute: AdminNotificacionesRoute,
  AdminPreciosRoute: AdminPreciosRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminSuscripcionesRoute: AdminSuscripcionesRoute,
  AdminWhatsappConfigRoute: AdminWhatsappConfigRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFacturasInvoiceIdRoute: AdminFacturasInvoiceIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OperatorRouteChildren {
  OperatorHoyRoute: typeof OperatorHoyRoute
  OperatorLoginRoute: typeof OperatorLoginRoute
  OperatorPendientesRoute: typeof OperatorPendientesRoute
  OperatorPerfilRoute: typeof OperatorPerfilRoute
  OperatorSemanaRoute: typeof OperatorSemanaRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  OperatorReservaBookingIdRoute: typeof OperatorReservaBookingIdRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorHoyRoute: OperatorHoyRoute,
  OperatorLoginRoute: OperatorLoginRoute,
  OperatorPendientesRoute: OperatorPendientesRoute,
  OperatorPerfilRoute: OperatorPerfilRoute,
  OperatorSemanaRoute: OperatorSemanaRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  OperatorReservaBookingIdRoute: OperatorReservaBookingIdRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  OperatorRoute: OperatorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
