/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDisponibilidadRouteImport } from './routes/admin.disponibilidad'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as PublicReservarRouteImport } from './routes/_public.reservar'
import { Route as PublicGraciasRouteImport } from './routes/_public.gracias'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisponibilidadRoute = AdminDisponibilidadRouteImport.update({
  id: '/disponibilidad',
  path: '/disponibilidad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const PublicReservarRoute = PublicReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGraciasRoute = PublicGraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/gracias': typeof PublicGraciasRoute
  '/reservar': typeof PublicReservarRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/gracias': typeof PublicGraciasRoute
  '/reservar': typeof PublicReservarRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/gracias': typeof PublicGraciasRoute
  '/_public/reservar': typeof PublicReservarRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/disponibilidad': typeof AdminDisponibilidadRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/gracias'
    | '/reservar'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/login'
    | '/admin/reservas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/gracias'
    | '/reservar'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/login'
    | '/admin/reservas'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/gracias'
    | '/_public/reservar'
    | '/admin/calendario'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/disponibilidad'
    | '/admin/login'
    | '/admin/reservas'
    | '/_public/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disponibilidad': {
      id: '/admin/disponibilidad'
      path: '/disponibilidad'
      fullPath: '/admin/disponibilidad'
      preLoaderRoute: typeof AdminDisponibilidadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/reservar': {
      id: '/_public/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof PublicReservarRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gracias': {
      id: '/_public/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof PublicGraciasRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicGraciasRoute: typeof PublicGraciasRoute
  PublicReservarRoute: typeof PublicReservarRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicGraciasRoute: PublicGraciasRoute,
  PublicReservarRoute: PublicReservarRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDisponibilidadRoute: typeof AdminDisponibilidadRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDisponibilidadRoute: AdminDisponibilidadRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
