// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azflxjuthcjmkhseycjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6Zmx4anV0aGNqbWtoc2V5Y2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzMjkzMTcsImV4cCI6MjA5MzkwNTMxN30.Q5S5HmupEssMPyPMyvStL1va12GDdxtenHX-Mj87_YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});