#!/usr/bin/env bash
# ============================================================================
# Washero — bundle Supabase Edge Functions into the self-hosted edge-runtime.
#
# Output layout (mounted to /home/deno/main in compose):
#   selfhost/edge-runtime/main/index.js          -> imports every function module (regenerated)
#   selfhost/edge-runtime/main/functions/<name>.js -> bundled function (each calls serve())
#
# Requires: Deno (https://deno.com/install) installed on the host.
# Usage:    bash selfhost/scripts/build-functions.sh   (or: make selfhost-functions)
# ============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$ROOT/supabase/functions"
OUT="$ROOT/selfhost/edge-runtime/main/functions"
IMPORT_MAP="$SRC/deno.json"

if ! command -v deno >/dev/null 2>&1; then
  echo "!! deno not found. Install it:  curl -fsSL https://deno.land/install.sh | sh" >&2;
  exit 1;
fi

mkdir -p "$OUT"
rm -f "$OUT"/*.js 2>/dev/null || true

BUNDLED=()
for fn in "$SRC"/*/index.ts; do
  [ -e "$fn" ] || continue;
  name="$(basename "$(dirname "$fn")")"
  echo "==> bundling: $name";
  if [ -f "$IMPORT_MAP" ]; then
    deno bundle --no-check --import-map="$IMPORT_MAP" "$fn" "$OUT/$name.js";
  else
    deno bundle --no-check "$fn" "$OUT/$name.js";
  fi;
  BUNDLED+=("$name");
done

# Regenerate the entrypoint with one import per bundled module. Each module calls
# serve()/Deno.serve itself, so plain imports are sufficient.
GEN="$ROOT/selfhost/edge-runtime/main/index.js";
{
  echo "// Generated by selfhost/scripts/build-functions.sh — do not edit by hand.";
  echo "// Each function module below calls serve() itself; importing registers it.";
  for name in "${BUNDLED[@]}"; do
    echo "import \"./functions/$name.js\";";
  done;
} > "$GEN"

echo "==> Bundled ${#BUNDLED[@]} functions into $OUT";
echo "==> Regenerated $GEN";
